# Setup
title:               Astral
tagline:             'blog'
description:         'myblog'
url:                 
baseurl:             'https://astral.jasadukun.com'

permalink:           /:title

# About/contact
author:
  name:              Mdmin
  url:               https://twitter.com/madmin
  email:             madmin@gmail.com

# Gems
plugins:  
  - jekyll-sitemap 

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
