# Setup
title:               Astral
tagline:             'blog'
description:         'myblog'
url:                 'https://astral.jasadukun.com'
baseurl:             ''   # kosong karena situs ada di root domain
permalink:           '/:title'

# About/contact
author:
  name:              'Madmin'
  url:               'https://twitter.com/madmin'
  email:             'madmin@gmail.com'

# Plugins
plugins:
  - jekyll-sitemap

# Custom vars
version:             '1.1.0'
google_analytics_id: ''   # contoh: UA-XXXX-Y
